export const DATABASE_CONSTANTS = {
  DEFAULT_MAX_POOL_CONNECTIONS: 5,
  DEFAULT_IDLE_TIMEOUT_MS: 30000,
  DEFAULT_CONNECTION_TIMEOUT_MS: 5000,
  MIGRATIONS_TABLE: '_migrations',
  TARGET_ENV_DEV: 'dev',
  TARGET_ENV_PROD: 'prod',
  TARGET_ENV_PRODUCTION: 'production',
  NOW_QUERY: 'SELECT NOW() as current_time',
} as const;
