name: Setup Template
on:
  push:
    branches: [main, master]

permissions:
  contents: write

jobs:
  setup:
    # Do not run if we are in the original template repository itself
    if: ${{ !contains(github.repository, 'api-service-template') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Replace placeholders
        run: |
          REPO_NAME=${{ github.event.repository.name }}
          TODAYS_DATE=$(date +'%Y-%m-%d')
          
          find . -type f ! -path '*/.git/*' ! -name 'setup-template.yml' -exec sed -i "s/{{REPO_NAME}}/$REPO_NAME/g" {} +
          find . -type f ! -path '*/.git/*' ! -name 'setup-template.yml' -exec sed -i "s/{{TODAYS_DATE}}/$TODAYS_DATE/g" {} +

      - name: Delete setup workflow
        run: |
          git rm .github/workflows/setup-template.yml

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "chore: bootstrap repository from template"
          git push
